/* ============================================================
   PA Announcement Generator — embedded data
   Extracted verbatim from PAH.html
   ============================================================ */

// ===== CODESHARE DATABASE =====
export const CODESHARE = {
  "TG002":"Turkish Airlines","TG003":"Turkish Airlines","TG004":"Gulf Air and Turkish Airlines","TG005":"Gulf Air and Turkish Airlines","TG008":"Turkish Airlines","TG009":"Turkish Airlines","TG020":"Turkish Airlines","TG021":"Turkish Airlines","TG028":"Turkish Airlines and Gulf Air","TG029":"Turkish Airlines and Gulf Air","TG040":"Turkish Airlines","TG041":"Turkish Airlines","TG042":"Turkish Airlines and Gulf Air","TG043":"Turkish Airlines and Gulf Air","TG044":"Gulf Air and Turkish Airlines","TG045":"Gulf Air and Turkish Airlines","TG046":"Turkish Airlines","TG047":"Turkish Airlines",
  "TG102":"Asiana Airlines and EVA AIR","TG103":"Asiana Airlines and EVA AIR","TG104":"EVA AIR","TG105":"EVA AIR","TG110":"Turkish Airlines, Gulf Air, Austrian Airlines and EVA AIR","TG111":"Turkish Airlines, Gulf Air, Austrian Airlines and EVA AIR","TG112":"Gulf Air and EVA AIR","TG113":"Gulf Air and EVA AIR","TG120":"Lufthansa, Austrian Airlines, EVA AIR and El Al","TG121":"Lufthansa, Austrian Airlines, EVA AIR and El Al","TG130":"Turkish Airlines, EVA AIR","TG131":"Turkish Airlines, EVA AIR","TG132":"Turkish Airlines, EVA AIR and Gulf Air","TG133":"Turkish Airlines, EVA AIR and Gulf Air","TG136":"Gulf Air and Lufthansa","TG137":"Gulf Air and Lufthansa",
  "TG201":"Asiana Airlines and EVA AIR","TG202":"Asiana Airlines and EVA AIR","TG203":"Air Canada, Austrian Airlines and El Al","TG204":"Air Canada, Austrian Airlines and El Al","TG205":"El Al","TG206":"El Al","TG207":"Gulf Air","TG208":"Gulf Air","TG211":"Gulf Air, Asiana Airlines, Austrian Airlines and El Al","TG212":"Gulf Air, Asiana Airlines, Austrian Airlines and El Al","TG215":"Gulf Air","TG216":"Gulf Air","TG217":"Turkish Airlines, Lufthansa, Austrian Airlines and El Al","TG218":"Turkish Airlines, Lufthansa, Austrian Airlines and El Al","TG221":"Asiana Airlines","TG222":"Asiana Airlines","TG225":"Air Canada","TG226":"Air Canada","TG241":"EVA AIR and Asiana Airlines","TG242":"EVA AIR and Asiana Airlines","TG249":"Turkish Airlines, Lufthansa, Austrian Airlines, EVA AIR, Gulf Air and El Al","TG250":"Turkish Airlines, Lufthansa, Austrian Airlines, EVA AIR, Gulf Air and El Al","TG259":"Turkish Airlines","TG260":"Turkish Airlines","TG263":"Turkish Airlines and Gulf Air","TG264":"Turkish Airlines and Gulf Air","TG267":"Turkish Airlines, Lufthansa and Austrian Airlines","TG268":"Turkish Airlines, Lufthansa and Austrian Airlines",
  "TG301":"Turkish Airlines, Asiana Airlines and Oman Air","TG302":"Turkish Airlines, Asiana Airlines and Oman Air","TG303":"Lufthansa and Austrian Airlines","TG304":"Lufthansa and Austrian Airlines","TG307":"Asiana Airlines","TG308":"Asiana Airlines","TG313":"ANA","TG314":"ANA","TG315":"ANA","TG316":"ANA","TG317":"ANA, EVA AIR, and Asiana Airlines","TG318":"ANA, EVA AIR, and Asiana Airlines","TG321":"Bangkok Airways and Air Canada","TG322":"Bangkok Airways and Air Canada","TG323":"ANA","TG324":"ANA","TG325":"ANA","TG326":"ANA","TG329":"ANA","TG330":"ANA","TG331":"ANA","TG332":"ANA","TG337":"Asiana Airlines and ANA","TG338":"Asiana Airlines and ANA","TG339":"Bangkok Airways","TG340":"Bangkok Airways","TG341":"Air Canada","TG342":"Air Canada","TG345":"Asiana Airlines and Air Canada","TG346":"Asiana Airlines and Air Canada","TG349":"Air Canada","TG350":"Air Canada","TG351":"EVA AIR","TG352":"EVA AIR",
  "TG401":"Bangkok Airways and Austrian Airlines","TG402":"Bangkok Airways and Austrian Airlines","TG403":"Bangkok Airways and Air Canada","TG404":"Bangkok Airways and Air Canada","TG407":"Bangkok Airways and Austrian Airlines","TG408":"Bangkok Airways and Austrian Airlines","TG409":"Austrian Airlines and Bangkok Airways","TG410":"Austrian Airlines and Bangkok Airways","TG413":"Kuwait Airways, Bangkok Airways and Air Canada","TG414":"Kuwait Airways, Bangkok Airways and Air Canada","TG415":"Malaysia Airlines, ANA, Turkish Airlines and Kuwait Airways","TG416":"Malaysia Airlines, ANA, Turkish Airlines and Kuwait Airways","TG417":"Lufthansa, Malaysia Airlines, Austrian Airlines, Gulf Air, Turkish Airlines","TG418":"Lufthansa, Malaysia Airlines, Austrian Airlines, Gulf Air, Turkish Airlines","TG425":"Lufthansa, Turkish Airlines and Austrian Airlines","TG426":"Lufthansa, Turkish Airlines and Austrian Airlines","TG431":"Asiana Airlines and Austrian Airlines","TG432":"Asiana Airlines and Austrian Airlines","TG433":"Austrian Airlines","TG434":"Austrian Airlines","TG435":"Gulf Air and Austrian Airlines","TG436":"Gulf Air and Austrian Airlines","TG439":"Austrian Airlines","TG440":"Austrian Airlines","TG461":"Turkish Airlines, Oman Air, Gulf Air and El Al","TG462":"Turkish Airlines, Oman Air, Gulf Air and El Al","TG465":"Gulf Air, Lufthansa, Turkish Airlines, Oman Air, Austrian Airlines and El Al","TG466":"Gulf Air, Lufthansa, Turkish Airlines, Oman Air, Austrian Airlines and El Al","TG471":"Lufthansa, Gulf Air, Oman Air, Austrian Airlines and El Al","TG472":"Lufthansa, Gulf Air, Oman Air, Austrian Airlines and El Al","TG475":"Gulf Air, Turkish Airlines, El Al and Oman Air","TG476":"Gulf Air, Turkish Airlines, El Al and Oman Air","TG481":"Turkish Airlines, Oman Air, Lufthansa, Austrian Airlines and El Al","TG482":"Turkish Airlines, Oman Air, Lufthansa, Austrian Airlines and El Al","TG483":"Turkish Airlines, Lufthansa and Austrian Airlines","TG484":"Turkish Airlines, Lufthansa and Austrian Airlines",
  "TG550":"Turkish Airlines and Air Canada","TG551":"Turkish Airlines and Air Canada","TG556":"Lufthansa, Austrian Airlines, Turkish Airlines, El Al and Oman Air","TG557":"Lufthansa, Austrian Airlines, Turkish Airlines, El Al and Oman Air","TG560":"Air Canada, Oman Air and Turkish Airlines","TG561":"Air Canada, Oman Air and Turkish Airlines","TG564":"Lufthansa, Austrian Airlines, Turkish Airlines and El Al","TG565":"Lufthansa, Austrian Airlines, Turkish Airlines and El Al","TG570":"Turkish Airlines","TG571":"Turkish Airlines","TG574":"Lufthansa and El Al","TG575":"Lufthansa and El Al","TG584":"Lufthansa","TG585":"Lufthansa","TG586":"Turkish Airlines","TG587":"Turkish Airlines",
  "TG600":"Air Canada and Turkish Airlines","TG601":"Air Canada and Turkish Airlines","TG602":"Austrian Airlines","TG603":"Austrian Airlines","TG612":"Shenzhen Airlines","TG613":"Shenzhen Airlines","TG614":"Bangkok Airways","TG615":"Bangkok Airways","TG618":"Shenzhen Airlines","TG619":"Shenzhen Airlines","TG620":"Air Canada, Lufthansa and Austrian Airlines","TG621":"Air Canada, Lufthansa and Austrian Airlines","TG622":"ANA, Turkish Airlines and El Al","TG623":"ANA, Turkish Airlines and El Al","TG624":"Austrian Airlines","TG625":"Austrian Airlines","TG628":"Gulf Air","TG629":"Gulf Air","TG632":"EVA AIR, Turkish Airlines and El Al","TG633":"EVA AIR, Turkish Airlines and El Al","TG634":"EVA AIR, Turkish Airlines and El Al","TG635":"EVA AIR, Turkish Airlines and El Al","TG636":"Lufthansa, EVA AIR and El Al","TG637":"Lufthansa, EVA AIR and El Al","TG638":"Air Canada, Gulf Air, Air New Zealand and Austrian Airlines","TG639":"Air Canada, Gulf Air, Air New Zealand and Austrian Airlines","TG640":"ANA and El Al","TG641":"ANA and El Al","TG642":"ANA","TG643":"ANA","TG644":"ANA and El Al","TG645":"ANA and El Al","TG648":"ANA, Turkish Airlines and El Al","TG649":"ANA, Turkish Airlines and El Al","TG652":"Asiana Airlines, Turkish Airlines and Oman Air","TG653":"Asiana Airlines, Turkish Airlines and Oman Air","TG656":"Asiana Airlines and Turkish Airlines","TG657":"Asiana Airlines and Turkish Airlines","TG658":"Asiana Airlines, Turkish Airlines, Oman Air and El Al","TG659":"Asiana Airlines, Turkish Airlines, Oman Air and El Al","TG660":"ANA","TG661":"ANA","TG662":"Bangkok Airways","TG663":"Bangkok Airways","TG664":"Bangkok Airways","TG665":"Bangkok Airways","TG668":"Bangkok Airways and Shenzhen Airlines","TG669":"Bangkok Airways and Shenzhen Airlines","TG670":"ANA and El Al","TG671":"ANA and El Al","TG672":"ANA, Turkish Airlines and El Al","TG673":"ANA, Turkish Airlines and El Al","TG676":"ANA, Air Canada and Turkish Airlines","TG677":"ANA, Air Canada and Turkish Airlines","TG682":"ANA and El Al","TG683":"ANA and El Al",
  "TG900":"Turkish Airlines","TG901":"Turkish Airlines","TG910":"Air Canada","TG911":"Air Canada","TG916":"EVA AIR","TG917":"EVA AIR","TG920":"Air Canada and TAP Air Portugal","TG921":"Air Canada and TAP Air Portugal","TG922":"TAP Air Portugal","TG923":"TAP Air Portugal","TG924":"TAP Air Portugal","TG925":"TAP Air Portugal","TG934":"TAP Air Portugal","TG935":"TAP Air Portugal","TG940":"TAP Air Portugal","TG941":"TAP Air Portugal","TG950":"Air Canada and TAP Air Portugal","TG951":"Air Canada and TAP Air Portugal","TG954":"TAP Air Portugal","TG955":"TAP Air Portugal","TG960":"Air Canada","TG961":"Air Canada","TG970":"Air Canada, Swiss International Airlines, and TAP Air Portugal","TG971":"Air Canada, Swiss International Airlines, and TAP Air Portugal"
};

// ===== AIRPORT DATABASE =====
export const AIRPORTS = {
  "LHR":{en:"London Heathrow Airport",th:"ท่าอากาศยานลอนดอน ฮีทโธรว์",city_en:"London",city_th:"ลอนดอน"},
  "FRA":{en:"Frankfurt Airport",th:"ท่าอากาศยานแฟรงก์เฟิร์ต",city_en:"Frankfurt",city_th:"แฟรงก์เฟิร์ต"},
  "MUC":{en:"Munich Airport",th:"ท่าอากาศยานมิวนิก",city_en:"Munich",city_th:"มิวนิก"},
  "CDG":{en:"Charles de Gaulle Airport",th:"ท่าอากาศยานชาร์ล เดอ โกล",city_en:"Paris",city_th:"ปารีส"},
  "ZRH":{en:"Zurich Airport",th:"ท่าอากาศยานซูริค",city_en:"Zurich",city_th:"ซูริค"},
  "BRU":{en:"Brussels Airport",th:"ท่าอากาศยานบรัสเซลส์",city_en:"Brussels",city_th:"บรัสเซลส์"},
  "AMS":{en:"Amsterdam Schiphol Airport",th:"ท่าอากาศยานอัมสเตอร์ดัม สคิปโฮล",city_en:"Amsterdam",city_th:"อัมสเตอร์ดัม"},
  "MXP":{en:"Milan Malpensa Airport",th:"ท่าอากาศยานมิลาน มัลเปนซา",city_en:"Milan",city_th:"มิลาน"},
  "CPH":{en:"Copenhagen Airport",th:"ท่าอากาศยานโคเปนเฮเกน",city_en:"Copenhagen",city_th:"โคเปนเฮเกน"},
  "OSL":{en:"Oslo Airport",th:"ท่าอากาศยานออสโล",city_en:"Oslo",city_th:"ออสโล"},
  "ARN":{en:"Stockholm Arlanda Airport",th:"ท่าอากาศยานสตอกโฮล์ม อาร์ลันดา",city_en:"Stockholm",city_th:"สตอกโฮล์ม"},
  "IST":{en:"Istanbul Airport",th:"ท่าอากาศยานอิสตันบูล",city_en:"Istanbul",city_th:"อิสตันบูล"},
  "NRT":{en:"Narita International Airport",th:"ท่าอากาศยานนาริตะ",city_en:"Tokyo",city_th:"โตเกียว"},
  "HND":{en:"Haneda Airport",th:"ท่าอากาศยานฮาเนดะ",city_en:"Tokyo",city_th:"โตเกียว"},
  "KIX":{en:"Kansai International Airport",th:"ท่าอากาศยานคันไซ",city_en:"Osaka",city_th:"โอซาก้า"},
  "NGO":{en:"Chubu Centrair International Airport",th:"ท่าอากาศยานชูบุ เซ็นแทรร์",city_en:"Nagoya",city_th:"นาโกย่า"},
  "FUK":{en:"Fukuoka Airport",th:"ท่าอากาศยานฟุกุโอกะ",city_en:"Fukuoka",city_th:"ฟุกุโอกะ"},
  "CTS":{en:"New Chitose Airport",th:"ท่าอากาศยานนิว ชิโตเสะ",city_en:"Sapporo",city_th:"ซัปโปโร"},
  "ICN":{en:"Incheon International Airport",th:"ท่าอากาศยานอินชอน",city_en:"Seoul",city_th:"โซล"},
  "TPE":{en:"Taiwan Taoyuan International Airport",th:"ท่าอากาศยานไต้หวัน เถาหยวน",city_en:"Taipei",city_th:"ไทเป"},
  "HKG":{en:"Hong Kong International Airport",th:"ท่าอากาศยานฮ่องกง",city_en:"Hong Kong",city_th:"ฮ่องกง"},
  "PEK":{en:"Beijing Capital International Airport",th:"ท่าอากาศยานปักกิ่ง",city_en:"Beijing",city_th:"ปักกิ่ง"},
  "PVG":{en:"Shanghai Pudong International Airport",th:"ท่าอากาศยานเซี่ยงไฮ้ ผู่ตง",city_en:"Shanghai",city_th:"เซี่ยงไฮ้"},
  "CAN":{en:"Guangzhou Baiyun International Airport",th:"ท่าอากาศยานกว่างโจว ไป๋หยุน",city_en:"Guangzhou",city_th:"กว่างโจว"},
  "TFU":{en:"Chengdu Tianfu International Airport",th:"ท่าอากาศยานเฉิงตู เทียนฟู่",city_en:"Chengdu",city_th:"เฉิงตู"},
  "KMG":{en:"Kunming Changshui International Airport",th:"ท่าอากาศยานคุนหมิง",city_en:"Kunming",city_th:"คุนหมิง"},
  "SIN":{en:"Singapore Changi Airport",th:"ท่าอากาศยานสิงคโปร์ ชางงี",city_en:"Singapore",city_th:"สิงคโปร์"},
  "KUL":{en:"Kuala Lumpur International Airport",th:"ท่าอากาศยานกัวลาลัมเปอร์",city_en:"Kuala Lumpur",city_th:"กัวลาลัมเปอร์"},
  "CGK":{en:"Soekarno-Hatta International Airport",th:"ท่าอากาศยานซูการ์โน-ฮัตตา",city_en:"Jakarta",city_th:"จาการ์ตา"},
  "DPS":{en:"Ngurah Rai International Airport",th:"ท่าอากาศยานงูระห์ไร",city_en:"Bali",city_th:"บาหลี"},
  "SYD":{en:"Sydney Kingsford Smith Airport",th:"ท่าอากาศยานซิดนีย์",city_en:"Sydney",city_th:"ซิดนีย์"},
  "MEL":{en:"Melbourne Airport",th:"ท่าอากาศยานเมลเบิร์น",city_en:"Melbourne",city_th:"เมลเบิร์น"},
  "PER":{en:"Perth Airport",th:"ท่าอากาศยานเพิร์ท",city_en:"Perth",city_th:"เพิร์ท"},
  "DEL":{en:"Indira Gandhi International Airport",th:"ท่าอากาศยานอินทิรา คานธี",city_en:"Delhi",city_th:"เดลี"},
  "BOM":{en:"Chhatrapati Shivaji Maharaj International Airport",th:"ท่าอากาศยานมุมไบ",city_en:"Mumbai",city_th:"มุมไบ"},
  "BLR":{en:"Kempegowda International Airport",th:"ท่าอากาศยานเบงกาลูรู",city_en:"Bengaluru",city_th:"เบงกาลูรู"},
  "MAA":{en:"Chennai International Airport",th:"ท่าอากาศยานเจนไน",city_en:"Chennai",city_th:"เจนไน"},
  "HYD":{en:"Rajiv Gandhi International Airport",th:"ท่าอากาศยานไฮเดอราบาด",city_en:"Hyderabad",city_th:"ไฮเดอราบาด"},
  "CCU":{en:"Netaji Subhas Chandra Bose International Airport",th:"ท่าอากาศยานโกลกาตา",city_en:"Kolkata",city_th:"โกลกาตา"},
  "KHI":{en:"Jinnah International Airport",th:"ท่าอากาศยานการาจี",city_en:"Karachi",city_th:"การาจี"},
  "LHE":{en:"Allama Iqbal International Airport",th:"ท่าอากาศยานลาฮอร์",city_en:"Lahore",city_th:"ลาฮอร์"},
  "ISB":{en:"Islamabad International Airport",th:"ท่าอากาศยานอิสลามาบาด",city_en:"Islamabad",city_th:"อิสลามาบาด"},
  "DAC":{en:"Hazrat Shahjalal International Airport",th:"ท่าอากาศยานธากา",city_en:"Dhaka",city_th:"ธากา"},
  "RGN":{en:"Yangon International Airport",th:"ท่าอากาศยานย่างกุ้ง",city_en:"Yangon",city_th:"ย่างกุ้ง"},
  "SGN":{en:"Tan Son Nhat International Airport",th:"ท่าอากาศยานเตินเซินเญิ้ต",city_en:"Ho Chi Minh City",city_th:"โฮจิมินห์"},
  "HAN":{en:"Noi Bai International Airport",th:"ท่าอากาศยานนอยบ่าย",city_en:"Hanoi",city_th:"ฮานอย"},
  "VTE":{en:"Wattay International Airport",th:"ท่าอากาศยานเวียงจันทน์",city_en:"Vientiane",city_th:"เวียงจันทน์"},
  "KTI":{en:"Techo International Airport",th:"ท่าอากาศยานพนมเปญ",city_en:"Phnom Penh",city_th:"พนมเปญ"},
  "MNL":{en:"Ninoy Aquino International Airport",th:"ท่าอากาศยานมะนิลา",city_en:"Manila",city_th:"มะนิลา"},
  "PEN":{en:"Penang International Airport",th:"ท่าอากาศยานปีนัง",city_en:"Penang",city_th:"ปีนัง"},
  "KTM":{en:"Tribhuvan International Airport",th:"ท่าอากาศยานกาฐมาณฑุ",city_en:"Kathmandu",city_th:"กาฐมาณฑุ"},
  "CMB":{en:"Bandaranaike International Airport",th:"ท่าอากาศยานโคลัมโบ",city_en:"Colombo",city_th:"โคลัมโบ"},
  "AMD":{en:"Sardar Vallabhbhai Patel International Airport",th:"ท่าอากาศยานอาห์เมดาบาด",city_en:"Ahmedabad",city_th:"อาห์เมดาบาด"},
  "KHH":{en:"Kaohsiung International Airport",th:"ท่าอากาศยานเกาสง",city_en:"Kaohsiung",city_th:"เกาสง"},
  "CNX":{en:"Chiang Mai International Airport",th:"ท่าอากาศยานเชียงใหม่",city_en:"Chiang Mai",city_th:"เชียงใหม่"},
  "CEI":{en:"Mae Fah Luang-Chiang Rai International Airport",th:"ท่าอากาศยานเชียงราย",city_en:"Chiang Rai",city_th:"เชียงราย"},
  "HKT":{en:"Phuket International Airport",th:"ท่าอากาศยานภูเก็ต",city_en:"Phuket",city_th:"ภูเก็ต"},
  "KBV":{en:"Krabi Airport",th:"ท่าอากาศยานกระบี่",city_en:"Krabi",city_th:"กระบี่"},
  "HDY":{en:"Hat Yai International Airport",th:"ท่าอากาศยานหาดใหญ่",city_en:"Hat Yai",city_th:"หาดใหญ่"},
  "KKC":{en:"Khon Kaen Airport",th:"ท่าอากาศยานขอนแก่น",city_en:"Khon Kaen",city_th:"ขอนแก่น"},
  "UTH":{en:"Udon Thani International Airport",th:"ท่าอากาศยานอุดรธานี",city_en:"Udon Thani",city_th:"อุดรธานี"},
  "UBP":{en:"Ubon Ratchathani Airport",th:"ท่าอากาศยานอุบลราชธานี",city_en:"Ubon Ratchathani",city_th:"อุบลราชธานี"},
  "GAY":{en:"Gaya Airport",th:"ท่าอากาศยานคยา",city_en:"Gaya",city_th:"คยา"}
};

// ===== FLIGHT DATABASE =====
export const FLIGHTS = {
  "TG910":{dest:"LHR",dep:"0045",h:11,m:30},"TG911":{dest:"BKK",dep:"1230",h:11,m:30},
  "TG916":{dest:"LHR",dep:"1245",h:11,m:30},"TG917":{dest:"BKK",dep:"2125",h:11,m:30},
  "TG920":{dest:"LHR",dep:"2345",h:12,m:30,via:"FRA"},"TG921":{dest:"BKK",dep:"1230",h:12,m:55},
  "TG924":{dest:"MUC",dep:"0050",h:11,m:15},"TG925":{dest:"BKK",dep:"1425",h:10,m:40},
  "TG930":{dest:"CDG",dep:"0005",h:12,m:5},"TG931":{dest:"BKK",dep:"1340",h:11,m:15},
  "TG934":{dest:"BRU",dep:"0005",h:12,m:10},"TG935":{dest:"BKK",dep:"1330",h:11,m:5},
  "TG936":{dest:"AMS",dep:"0430",h:11,m:45},"TG937":{dest:"BKK",dep:"1400",h:11,m:20},
  "TG940":{dest:"MXP",dep:"0040",h:11,m:55},"TG941":{dest:"BKK",dep:"1405",h:10,m:50},
  "TG950":{dest:"CPH",dep:"0050",h:11,m:50},"TG951":{dest:"BKK",dep:"1425",h:10,m:35},
  "TG954":{dest:"OSL",dep:"0105",h:11,m:20},"TG955":{dest:"BKK",dep:"1345",h:10,m:30},
  "TG960":{dest:"ARN",dep:"0005",h:11,m:20},"TG961":{dest:"BKK",dep:"1350",h:10,m:0},
  "TG970":{dest:"ZRH",dep:"0055",h:11,m:55},"TG971":{dest:"BKK",dep:"1330",h:10,m:45},
  "TG900":{dest:"IST",dep:"2350",h:9,m:45},"TG901":{dest:"BKK",dep:"1630",h:9,m:10},
  "TG622":{dest:"KIX",dep:"2359",h:5,m:31},"TG623":{dest:"BKK",dep:"1145",h:5,m:50},
  "TG640":{dest:"NRT",dep:"2210",h:5,m:10},"TG641":{dest:"BKK",dep:"1050",h:6,m:30},
  "TG642":{dest:"NRT",dep:"2350",h:6,m:20},"TG643":{dest:"BKK",dep:"1200",h:6,m:30},
  "TG644":{dest:"NGO",dep:"0005",h:5,m:55},"TG645":{dest:"BKK",dep:"1100",h:6,m:0},
  "TG648":{dest:"FUK",dep:"0040",h:5,m:20},"TG649":{dest:"BKK",dep:"1135",h:5,m:30},
  "TG660":{dest:"HND",dep:"1300",h:6,m:10},"TG661":{dest:"BKK",dep:"0020",h:6,m:30},
  "TG670":{dest:"CTS",dep:"2345",h:6,m:45},"TG671":{dest:"BKK",dep:"1030",h:7,m:0},
  "TG672":{dest:"KIX",dep:"0825",h:5,m:30},"TG673":{dest:"BKK",dep:"1735",h:5,m:50},
  "TG676":{dest:"NRT",dep:"0745",h:6,m:10},"TG677":{dest:"BKK",dep:"1725",h:6,m:30},
  "TG682":{dest:"HND",dep:"2245",h:6,m:10},"TG683":{dest:"BKK",dep:"1035",h:6,m:30},
  "TG652":{dest:"ICN",dep:"0800",h:5,m:25},"TG653":{dest:"BKK",dep:"1655",h:5,m:50},
  "TG656":{dest:"ICN",dep:"2330",h:5,m:25},"TG657":{dest:"BKK",dep:"1020",h:5,m:50},
  "TG658":{dest:"ICN",dep:"2310",h:5,m:25},"TG659":{dest:"BKK",dep:"0935",h:5,m:50},
  "TG632":{dest:"TPE",dep:"0825",h:3,m:40},"TG633":{dest:"BKK",dep:"1405",h:3,m:45},
  "TG638":{dest:"HKG",dep:"1400",h:2,m:45},"TG639":{dest:"BKK",dep:"1905",h:2,m:40},
  "TG600":{dest:"HKG",dep:"0800",h:2,m:45},"TG601":{dest:"BKK",dep:"1245",h:2,m:40},
  "TG614":{dest:"PEK",dep:"1000",h:4,m:45},"TG615":{dest:"BKK",dep:"1705",h:4,m:10},
  "TG662":{dest:"PVG",dep:"0030",h:4,m:15},"TG663":{dest:"BKK",dep:"0730",h:4,m:35},
  "TG403":{dest:"SIN",dep:"0800",h:2,m:15},"TG404":{dest:"BKK",dep:"1225",h:2,m:20},
  "TG431":{dest:"DPS",dep:"0935",h:4,m:20},"TG432":{dest:"BKK",dep:"1655",h:4,m:10},
  "TG465":{dest:"SYD",dep:"0830",h:9,m:0},"TG466":{dest:"BKK",dep:"1000",h:8,m:20},
  "TG475":{dest:"MEL",dep:"0830",h:9,m:30},"TG476":{dest:"BKK",dep:"1330",h:8,m:50},
  "TG315":{dest:"DEL",dep:"1850",h:4,m:0},"TG316":{dest:"BKK",dep:"2330",h:4,m:55},
  "TG317":{dest:"BOM",dep:"1855",h:4,m:0},"TG318":{dest:"BKK",dep:"2335",h:5,m:0},
  "TG341":{dest:"KHI",dep:"1900",h:5,m:0},"TG342":{dest:"BKK",dep:"2330",h:4,m:50},
  "TG345":{dest:"LHE",dep:"1950",h:4,m:40},"TG346":{dest:"BKK",dep:"2340",h:4,m:30}
};
